mode: subtitle  #demo or subtitle
preprocessing:
    load: False
    substitle_file: data/temp # AnotherMissOh_Sence_Subtitle
    output_path: data/output/preprocessed.json
    coreference: gold

extraction:
    load: False
    oie: stanford
    frame: frameBERT
    output_path: data/output/extracted.json

background:
    load: False
    input_path: data/background.txt
    output_path: data/output/background_KB.json

graph:
    character_name: data/character.txt
    use_backKB: True
    visualization: all  # all, frame, triple, None
    package_path: C:/Program Files (x86)/Graphviz2.38/bin/  # https://graphviz.gitlab.io/_pages/Download/Download_windows.html에서 설치 후 Graphviz 경로
    graph_path: data/output/graphs
    json_path: data/output/graph.json
    character: all
    only_use: None
